# Generated by Django 4.0.6 on 2022-08-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_sales_contact'),
        ('contracts', '0005_alter_contract_client_alter_contract_sales_contact'),
        ('events', '0003_alter_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='contracts.contract'),
        ),
    ]
