# Generated by Django 4.0.6 on 2022-08-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_user'),
        ('clients', '0002_alter_client_sales_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to={'role': 'SALES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='users.employee'),
        ),
    ]
